apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      containers:
      - name: python-backend
        image: python:3.8-slim
        command:
        - "python"
        - "-m"
        - "http.server"
        - "8080"
        ports:
        - containerPort: 8080

